package com.gestaoigrejaemcelula.demo.domain.enums;

public enum CargoMembro {
    DIACONO,
    DIREITO_DIACONATO,
    LIDER_GRUPO_MISSIONARIO_HOMEM,
    LIDER_GRUPO_MISSIONARIO_MULHER,
    LIDER_GRUPO_MISSIONARIO_CRIANCA,
    LIDER_GRUPO_MISSIONARIO_JOVEM,
    LIDER,
    SECRETARIA,
    TESOURARIA_FINANCEIRO,
    LIDER_GRUPO_CASAIS
}
